### ISSUE TITLE
Error after clicking following

### ISSUE THREAD

**Issue by jessemarco** [r-a-y/buddypress-followers#113]
1. Clean Installation
2. Default Theme 2019, buddypress ,your plugin and  **WP 5.3.2** 

Server APACHE2
OS Ubuntu 18.04

Thank you for har working

**Fatal error:** Uncaught Error: [] operator not supported for strings in /var/www/html/wp/wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php:308 Stack trace: #0 /var/www/html/wp/wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php(122): bp_follow_new_follow_email_notification(Array) #1 /var/www/html/wp/wp-includes/class-wp-hook.php(286): bp_follow_notifications_add_on_follow(Object(BP_Follow)) #2 /var/www/html/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /var/www/html/wp/wp-includes/plugin.php(531): WP_Hook->do_action(Array) #4 /var/www/html/wp/wp-content/plugins/buddypress-followers/_inc/bp-follow-functions.php(43): do_action_ref_array('bp_follow_start...', Array) #5 /var/www/html/wp/wp-content/plugins/buddypress-followers/_inc/bp-follow-actions.php(38): bp_follow_start_following(Array) #6 /var/www/html/wp/wp-includes/class-wp-hook.php(286): bp_follow_action_start('') #7 /var/www/html/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, in /var/www/html/wp/wp-content/plugins/buddypress-followers/_inc/bp-follow-notifications.php on line 308

**Comment by jessemarco** [comment]
It looks like fixed this issue in master repo. Hope you gonna release soon in wp plugin directory as well.

**Comment by BlopeetyBlop** [comment]
This issue still exists.
